DATA_PATH: "datasets"
TRAIN_DIR: "train"
VALID_DIR: "valid"
TEST_DIR: "test"
PROBLEM: "uc_infeksi_chron_tb"
IMAGE_SIZE: 299
IMAGE_CHANNELS: 3 #RGB
PIN_MEMORY: false
IS_SHUFFLE: true
SEED: 42
SPLIT_RATIO: [0.8, 0.1, 0.1]
SAMPLING:
  IS_SAMPLING: false
  SAMPLING_NUMBER: 50

CATEGORIES: ["uc", "infeksi", "chron", "tb"] # make sure the categories are in the same order as the categories in the dataset
UC_SOURCE: ["limuc_cropped_2", "changsu_cropped"]
