NUM_WORKERS: 0
BATCH_SIZE: 16
NUM_EPOCHS: 100
LEARNING_RATE: 0.000025
WEIGHT_DECAY: 0.00015
MOMENTUM: 0.9
DROPOUT_RATE: 0.45
EARLY_STOPPING_PATIENCE: 30
AVERAGE: "macro"
PRINT_EVERY: 9999
SAVE_PATH: "artifacts/uc_infeksi_chron_tb/densenet121"
SAVE_MODEL: true
SAVE_METRICS: true
SAVE_PATIENCE: 1
SHUFFLE: True
